server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Desktop/Project/CATXI_MSA/git-local-repo
          default-label: master


