server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "q9wgeHTWsbeRlSFfx2bMLfqLfP+QAl3v0L2FZ/F26CnMk0zlm+TqtqFEorqD54Nbzh4xqTa7kPgu2QTffrQ48A=="
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
            - id: chat-service-ws
              uri: lb:ws://CHAT-SERVICE
              predicates:
                 - Path=/chat-service/connect
                 - Header=Upgrade, websocket
              filters:
                  - StripPrefix=1
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notification-service/**
            - id: map-service
              uri: lb://MAP-SERVICE
              predicates:
                - Path=/map-service/**
          globalcors:
            cors-configurations:
              '[/**]':
                          allowedOrigins:
                            - "http://localhost:5173"
                            - "https://catxi.kro.kr"
                            - "https://catxi-university-taxi-b0936.web.app"
                          allowedMethods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
                          allowedHeaders: [ "*" ]
                          exposedHeaders: [ "*" ]
                          allowCredentials: true
                          maxAge: 3600
            add-to-simple-url-handler-mapping: true


management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - httpexchanges